const $=id=>document.getElementById(id);const screens=["singleSetup","singlePass","singleRole","singleDiscuss","singleVotePass","singleVote","singleResult","singleFinal"];function show(id){screens.forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden")}function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}function maxImp(n){return n<3?1:1+Math.floor((n-3)/3)}
const words=[
{w:"Kucing",c:"Hewan",q:["Bulu","Mengeong","Peliharaan"]},{w:"Harimau",c:"Hewan",q:["Belang","Hutan","Pemangsa"]},{w:"Gajah",c:"Hewan",q:["Belalai","Besar","Afrika"]},
{w:"Pantai",c:"Tempat",q:["Air","Pasir","Ombak"]},{w:"Gunung",c:"Tempat",q:["Tinggi","Dingin","Mendaki"]},{w:"Bandara",c:"Tempat",q:["Pesawat","Terminal","Perjalanan"]},
{w:"Payung",c:"Benda",q:["Hujan","Pegangan","Lipat"]},{w:"Kamera",c:"Benda",q:["Foto","Lensa","Memotret"]},{w:"Kulkas",c:"Benda",q:["Dingin","Dapur","Makanan"]},
{w:"Bakso",c:"Makanan",q:["Kuah","Bulat","Daging"]},{w:"Rendang",c:"Makanan",q:["Daging","Rempah","Padang"]},{w:"Sate",c:"Makanan",q:["Tusuk","Bakar","Daging"]},
{w:"Mangga",c:"Buah",q:["Manis","Kuning","Pohon"]},{w:"Apel",c:"Buah",q:["Merah","Renyah","Bulat"]},{w:"Durian",c:"Buah",q:["Berduri","Aroma","Krim"]},
{w:"Mobil",c:"Kendaraan",q:["Empat roda","Setir","Jalan"]},{w:"Kereta",c:"Kendaraan",q:["Rel","Gerbong","Stasiun"]},{w:"Pesawat",c:"Kendaraan",q:["Terbang","Sayap","Bandara"]},
{w:"Dokter",c:"Pekerjaan",q:["Pasien","Rumah sakit","Obat"]},{w:"Guru",c:"Pekerjaan",q:["Sekolah","Mengajar","Murid"]},{w:"Pilot",c:"Pekerjaan",q:["Pesawat","Kokpit","Terbang"]},
{w:"Sepak Bola",c:"Olahraga",q:["Bola","Gawang","Lapangan"]},{w:"Badminton",c:"Olahraga",q:["Raket","Kok","Net"]},{w:"Renang",c:"Olahraga",q:["Air","Kolam","Gaya"]}];
let players=[],impCount=1,roles=[],roleI=0,voteI=0,votes={},chosen=null,word=null,localMatchOver=false;
function render(){ $("singlePlayers").innerHTML=players.map((p,i)=>`<div class="player-row"><div class="player-left"><div class="avatar">${esc(p.name[0].toUpperCase())}</div><div><div class="player-name">${esc(p.name)}</div><div class="you">${p.score||0} poin</div></div></div><button class="remove-single" data-i="${i}">Hapus</button></div>`).join("");$("singlePlayers").querySelectorAll(".remove-single").forEach(b=>b.onclick=()=>{players.splice(+b.dataset.i,1);render()});updateImp()}
function updateImp(){const m=maxImp(players.length);impCount=Math.max(1,Math.min(impCount,m));$("singleImp").textContent=impCount;$("singleImpHelp").textContent=`${impCount} impostor dari ${players.length} pemain`;$("singleMinus").disabled=impCount<=1;$("singlePlus").disabled=impCount>=m}
$("addPlayer").onclick=()=>{const n=$("singleName").value.trim().replace(/\s+/g," ").slice(0,20);if(!n||players.some(p=>p.name.toLowerCase()===n.toLowerCase()))return;players.push({name:n,score:0});$("singleName").value="";render()};$("singleMinus").onclick=()=>{if(impCount>1)impCount--;updateImp()};$("singlePlus").onclick=()=>{impCount++;updateImp()};
function pickWord(){const c=$("singleCategory").value,a=c==="Random"?words:words.filter(x=>x.c===c);return a[Math.floor(Math.random()*a.length)]}
$("singleStart").onclick=()=>{if(players.length<3){$("singleMsg").textContent="Minimal 3 pemain.";return}word=pickWord();const idx=[...players.keys()].sort(()=>Math.random()-.5),imps=new Set(idx.slice(0,impCount));roles=players.map((p,i)=>({...p,role:imps.has(i)?"impostor":"civilian",clue:[...word.q].sort(()=>Math.random()-.5).slice(0,2),alive:true}));localMatchOver=false;roleI=0;passRole()};
function passRole(){show("singlePass");$("passName").textContent=roles[roleI].name}$("openRole").onclick=()=>{const r=roles[roleI];show("singleRole");$("rolePlayer").textContent=r.name;$("localRoleCard").classList.toggle("impostor",r.role==="impostor");$("localRoleName").textContent=r.role==="impostor"?"IMPOSTOR":"WARGA";$("localCategory").textContent=word.c;$("localSecretLabel").textContent=r.role==="impostor"?"CLUE":"KATA RAHASIA";$("localSecret").textContent=r.role==="impostor"?r.clue.join(" • "):word.w;$("localDesc").textContent=r.role==="impostor"?"Kamu adalah Impostor. Kamu tidak tahu kata rahasianya.":"Jangan sebut kata secara langsung."};$("hideRole").onclick=()=>{roleI++;if(roleI>=roles.length)show("singleDiscuss");else passRole()};
$("beginLocalVote").onclick=()=>{voteI=0;votes={};while(voteI<roles.length&&!roles[voteI].alive)voteI++;votePass()};function votePass(){show("singleVotePass");$("votePassName").textContent=roles[voteI].name}$("openLocalVote").onclick=()=>{chosen=null;$("saveLocalVote").disabled=true;$("voteName").textContent=roles[voteI].name;$("localVoteOptions").innerHTML=roles.map((p,i)=>(i===voteI||!p.alive)?"":`<button class="vote-option" data-i="${i}"><span class="vote-radio"></span><span class="vote-avatar">${esc(p.name[0].toUpperCase())}</span><span class="vote-player-name">${esc(p.name)}</span></button>`).join("");$("localVoteOptions").querySelectorAll(".vote-option").forEach(b=>b.onclick=()=>{$("localVoteOptions").querySelectorAll(".vote-option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");chosen=+b.dataset.i;$("saveLocalVote").disabled=false});show("singleVote")};$("saveLocalVote").onclick=()=>{votes[voteI]=chosen;voteI++;while(voteI<roles.length&&!roles[voteI].alive)voteI++;if(voteI>=roles.length)result();else votePass()};
function scoreboard(){return players.map(p=>({name:p.name,score:p.score||0})).sort((a,b)=>b.score-a.score)}function drawScore(target){target.innerHTML=scoreboard().map((p,i)=>`<div class="score-row"><div class="score-left"><span class="rank">${i+1}</span><span class="score-name">${esc(p.name)}</span></div><span class="score-points">${p.score} poin</span></div>`).join("")}
function result(){const counts={};Object.values(votes).forEach(i=>counts[i]=(counts[i]||0)+1);const rows=Object.entries(counts).map(([i,v])=>[+i,v]).sort((a,b)=>b[1]-a[1]),top=rows[0]?.[1]||0,tops=rows.filter(x=>x[1]===top),tie=tops.length!==1,elim=tie?null:roles[tops[0][0]];if(elim)elim.alive=false;Object.entries(votes).forEach(([v,t])=>{if(roles[t].role==="impostor")players[v].score=(players[v].score||0)+25});const aliveImp=roles.filter(r=>r.alive&&r.role==="impostor").length,aliveCiv=roles.filter(r=>r.alive&&r.role==="civilian").length;let winner="continue";if(aliveImp===0){winner="civilian";localMatchOver=true}else if(aliveImp>=aliveCiv){winner="impostor";localMatchOver=true}else localMatchOver=false;if(localMatchOver){roles.forEach((r,i)=>{if(winner==="civilian"&&r.role==="civilian")players[i].score+=100;if(winner==="impostor"&&r.role==="impostor")players[i].score+=200})}$("localWinner").textContent=localMatchOver?(winner==="civilian"?"Warga Menang Pertandingan!":"Impostor Menang Pertandingan!"):"Ronde Selesai";$("localElim").textContent=tie?"Voting Seri":elim.name;$("localDetail").textContent=tie?"Tidak ada eliminasi.":`${elim.name} adalah ${elim.role==="impostor"?"IMPOSTOR":"WARGA"}.`;$("localWord").textContent=localMatchOver?word.w:"Tetap rahasia";$("localCatResult").textContent=word.c;drawScore($("localScore"));$("localAgain").textContent=localMatchOver?"Main Lagi":"Lanjut Ronde";show("singleResult")}
$("localAgain").onclick=()=>{if(localMatchOver){show("singleSetup");render()}else{show("singleDiscuss")}};$("localFinish").onclick=()=>{$("localPodium").innerHTML=scoreboard().map((p,i)=>`<div class="podium-row"><span class="podium-name">${i===0?"🏆 ":""}${i+1}. ${esc(p.name)}</span><span class="podium-score">${p.score} poin</span></div>`).join("");show("singleFinal")};render();